---
- name: Bootstrapping talos in docker
  hosts: localhost
  become: true
  become_user: root
  vars:
    name: bootstrap
    endpoint: '{{ ansible_default_ipv4.address }}'
    ports:
      - 67:67/udp
      - 69:69/udp
      - 8081:8081/tcp
      - 51821:51821/udp
    workers: 0
    config_patch: '[{"op": "add", "path": "/cluster/allowSchedulingOnControlPlanes", "value": true}]'
  roles:
    - andrewrothstein.kubectl
    - andrewrothstein.talos
    - andrewrothstein.cluster_api
  tasks:
    - name: Building a bootstrap talos cluster in docker
      ansible.builtin.shell: |-
        talosctl cluster create
          {%- if name %} \
          --name {{ name | quote }}
          {%- endif %}
          {%- if ports %} \
          -p {{ ports | join(",") | quote }}
          {%- endif %}
          {%- if controlplanes is defined %} \
          --controlplanes {{ controlplanes | int }}
          {%- endif %}
          {%- if workers is defined %} \
          --workers {{ workers | int }}
          {%- endif %}
          {%- if config_patch %} \
          --config-patch {{ config_patch | quote }}
          {%- endif %}
          {%- if endpoint %} \
          --endpoint {{ endpoint | quote }}
          {%- endif %}
